[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qt.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qt.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hypr.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.mako]
input_path = '~/.config/matugen/templates/mako.mustache'
output_path = '~/.config/mako/config'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.mustache'
output_path = '~/.config/rofi/colors.rasi'

[config]
reload_apps = true
set_wallpaper = false

[config.custom_colors]
red = "#de1b04"
orange = "#e36701"
yellow = "#fabd2f"
green = "#f0aa06"
blue = "#0643a2"
cyan = "#6cd7c5"
magenta = "#bf4e6d"

[config.reload_apps_list]
gtk_theme = true
